---
- hosts: all

  vars:

    # brew cask
    applications:
      - authy # nice authenticator app
      - brave-browser-dev # chrome without adds and tracking
      - clipy # nice clipboard utility
      - cyberduck # file transfer app
      - docker
      - font-hack-nerd-font
      - google-cloud-sdk
      - gpg-suite
      - iterm2
      - karabiner-elements
      - keybase
      - minikube
      - slack-beta
      - spotify
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager # 
      - virtualbox # | https://www.virtualbox.org/
      - visual-studio-code
      - vlc 

    install_oh_my_zsh:  true

    brew_taps:
      - caskroom/cask
      - caskroom/versions # for sublime-text3
      - homebrew/binary
      - homebrew/dupes # gnu grep
      - homebrew/versions 

    # brew  
    brew_utils:
      - ansible # most likely already installed att this point but better safe than sorry
      - autoconf # gnu autoconf
      - automake
      - awscli # aws command line u†ilities
      - base64 # all your base64 are belong to us
      - bat # a better cat
      - ctop # top command for docker containers
      - fzf # a command-line fuzzy finder
      - gnupg #  a complete and free implementation of the OpenPGP standard
      - gnutls #  a secure communications library implementing the SSL, TLS and DTLS protocols
      - htop # a prettier top
      - git
      - go # golang https://ahmadawais.com/install-go-lang-on-macos-with-homebrew/
      - hugo # framework for building static sites
      - imagemagick
      - node
      - ntfs-3g # ntfs support for os x
      - pinentry # needed for yubikey signing
      - google-chrome # always handy to have
      - handbrake # vid compression 
      - iterm2 
      - jumpcut # awesome clipboard
      - karabiner # Keyboard customization
      - autoconf
      - autojump # quickly navigate from cmd line
      - bash # Bash 4
      - boot2docker # for running docker on osx
      - brew-cask
      - cowsay # amazing
      - coreutils # Install GNU core utilities (those that come with OS X are outdated)
      - docker # | https://docs.docker.com/installation/mac/
      - findutils  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
      - git
      - go
      - gpg
      - hub # github
      - mtr # better traceroute
      - node
      - npm
      - openssl
      - packer
      - python
      - vim
      - wget
      - zsh

    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:
    
    - name: Check Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false

    - name: Instal required Homebrew Taps
      shell: brew tap {{ item }}
      with_items: brew_taps

    - name: Check homebrew-cask is installed
      stat: path=/usr/local/bin/brew-cask.rb
      register: brew_cask_installed

    - name: Install homebrew-cask
      shell: brew install brew-cask
      when: brew_cask_installed.stat.exists == false

    ### UTILS

    - name: Install libraries/utils with homebrew
      homebrew: name={{ item }} state=present
      with_items: brew_utils
    
    - name: Cleanup after brewing
      shell: brew cleanup


    ### APPZ

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true
    
    - name: Install Apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    ### ZSH radness 

    - name: Determine if zsh is default/current shell
      shell: echo $SHELL
      register: current_shell

    - name: Enable zsh in /etc/shells
      shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      when: current_shell.stdout != '/usr/local/bin/zsh'    
      #" unbreak my syntax highlighting...

    - name: Set zsh as default shell
      shell: chsh -s {{ zsh_path }}
      when: current_shell.stdout != '/usr/local/bin/zsh'
      sudo: true

    - name: Use GNU tools instead of osx counterparts (grep find etc) 
      shell: echo 'export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH' >> ~/.zshrc


    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      sudo: false
      when: install_oh_my_zsh == true
      tags: install_oh_my_zsh


    ### OSX SETTINGS

    - name: Configure System Settings
      script: scripts/system_settings.sh
      sudo: true

    ## POST INSTALL STEPS / Cask gotchas
    #
    # require manual intervention!
    #
    
